apiVersion: v1
kind: Pod
metadata:
  name: server-mesher
  annotations:
    sidecar.mesher.io/inject: "yes"
    sidecar.mesher.io/discoveryType: "sc"
    sidecar.mesher.io/serverType: "yes"
  labels:
    app: default
spec:
  containers:
    - name: server
      image: savita3020/server-io-go
      imagePullPolicy: Always
      ports:
        - containerPort: 9999